package com.softdesign.devintensive.utils;

public interface ConstantManager {
    String USER_PHONE_KEY = "USER_1_KEY";
    String USER_MAIL_KEY = "USER_2_KEY";
    String USER_VK_KEY = "USER_3_KEY";
    String USER_GIT_KEY = "USER_4_KEY";
    String USER_BIO_KEY = "USER_5_KEY";
    String USER_PHOTO_KEY = "USER_101_KEY";
    String USER_AVATAR_KEY = "USER_102_KEY";

    String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";
    String USER_ID_KEY = "USER_ID_KEY";

    String USER_RATING_VALUE = "USER_RATING_VALUE";
    String USER_CODE_LINES_VALUE = "USER_CODE_LINES_VALUE";
    String USER_PROJECTS_VALUE = "USER_PROJECTS_VALUE";

    int LOAD_PROFILE_PHOTO = 1;
    int REQUEST_CAMERA_PICTURE = 101;
    int REQUEST_GALLERY_PICTURE = 102;
    int PERMISSION_REQUEST_SETTINGS_CODE = 1001;
    int CAMERA_REQUEST_PERMISSION_CODE = 1002;
}
